CREATE TABLE transactions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  amount FLOAT,
  currency VARCHAR(255),
  hash VARCHAR(255),
  wallet VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  platform VARCHAR(255),
  website VARCHAR(255),
  status VARCHAR(255)
);